# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 90, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 180, 131, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 280, 131, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 380, 131, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 260, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 360, 91, 16))
        self.label_5.setObjectName("label_5")
        self.timeEdit = QtWidgets.QTimeEdit(self.frame)
        self.timeEdit.setGeometry(QtCore.QRect(40, 130, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.frame)
        self.timeEdit_2.setGeometry(QtCore.QRect(40, 220, 118, 22))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.frame)
        self.timeEdit_3.setGeometry(QtCore.QRect(40, 320, 118, 22))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.frame)
        self.timeEdit_4.setGeometry(QtCore.QRect(40, 420, 118, 22))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(500, 110, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(500, 160, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(500, 210, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(500, 260, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(500, 310, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(670, 110, 55, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(670, 160, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(670, 210, 55, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(670, 260, 55, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(670, 310, 55, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(550, 100, 111, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(550, 150, 111, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(550, 200, 111, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(550, 250, 111, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(550, 300, 111, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1, 1, 2, 2))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(520, 390, 141, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(520, 420, 221, 16))
        self.label_17.setObjectName("label_17")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(210, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 200, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 300, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 400, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(18, 11, 49, 16))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "เบิกอาวุธ"))
        self.label_3.setText(_translate("MainWindow", "คืนอาวุธ"))
        self.label_4.setText(_translate("MainWindow", "แจ้งอาวุธชำรุด"))
        self.label_5.setText(_translate("MainWindow", "แจ้งอาวุธสูญหาย"))
        self.label_6.setText(_translate("MainWindow", "คงเดิม"))
        self.label_7.setText(_translate("MainWindow", "เบิก"))
        self.label_8.setText(_translate("MainWindow", "ชำรุด"))
        self.label_9.setText(_translate("MainWindow", "สูญหาย"))
        self.label_10.setText(_translate("MainWindow", "คงเหลือ"))
        self.label_11.setText(_translate("MainWindow", "กระบอก"))
        self.label_12.setText(_translate("MainWindow", "กระบอก"))
        self.label_13.setText(_translate("MainWindow", "กระบอก"))
        self.label_14.setText(_translate("MainWindow", "กระบอก"))
        self.label_15.setText(_translate("MainWindow", "กระบอก"))
        self.label_16.setText(_translate("MainWindow", "ติดต่อเจ้าหน้าที่"))
        self.label_17.setText(_translate("MainWindow", "ร.ท.อนันตศักดิ์ บุญพิทักษ์"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton_2.setText(_translate("MainWindow", "OK"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.pushButton_4.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "คลังอาวุธ"))

#function Click button
        self.pushButton.clicked.connect(self.insert)
        self.pushButton_2.clicked.connect(self.)
        self.pushButton_3.clicked.connect(self.)
        
        # Show data 
        self.lineEdit_5.setPlaceholderText(get_data())
        self.lineEdit_6.setPlaceholderText(get_pickup())
        self.lineEdit_7.setPlaceholderText(get_broken())
        self.lineEdit_8.setPlaceholderText(get_lost())
        self.lineEdit_9.setPlaceholderText(get_remaining())
        
        
# Pick up        
    def insert(self):
        insert_data()

    def insert(self)
        
        
        
        
        

# DATABASE
import mysql.connector
# Done
def ConnectorMysql():

    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="",
        database="db",
        # auth_plugin='mysql_native_password'
    )
    # print("Connect database success !!")
    return mydb

# All DATA
# Done
def get_data():
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = f'SELECT SUM(pickup+broken+lost+remaining) FROM gun'
    mycursor.execute(sql)
    myresult = mycursor.fetchall()
    x = str(myresult[0][0])
    print("data")
    print(x)
    return x

# Done
def get_pickup():
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = f'SELECT SUM(pickup) FROM gun'
    mycursor.execute(sql)
    myresult = mycursor.fetchall()
    x = str(myresult[0][0])
    print("pickup")
    print(x)
    return x

# Done
def get_broken():
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = f'SELECT SUM(broken) FROM gun'
    mycursor.execute(sql)
    myresult = mycursor.fetchall()
    x = str(myresult[0][0])
    print("broken")
    print(x)    
    return x 
   
# Done
def get_lost():
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = f'SELECT SUM(lost) FROM gun'
    mycursor.execute(sql)
    myresult = mycursor.fetchall()
    x = str(myresult[0][0])
    print("lost")
    print(x)
    return x

# Done
def get_remaining():
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = f'SELECT SUM(remaining) FROM gun'
    mycursor.execute(sql)
    myresult = mycursor.fetchall()
    x = str(myresult[0][0])
    print("remaining")
    print(x)    
    return x

# Done
def get_alldata():
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = ("SELECT * FROM gun")
    mycursor.execute(sql)
    myresult = mycursor.fetchall()

    print(myresult)
    return myresult


def insert_data(uname, pickup, broken, lost, remaining, nogun):
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = "INSERT INTO gun (uname, pickup, broken, lost, remaining, nogun) VALUES (%s ,%s, %s,%s, %s, %s)"
    val = (uname, pickup, broken, lost, remaining, nogun)
    mycursor.execute(sql, val)
    print('success')
    mydb.commit()
    mycursor.close()
    mydb.close()


# localhost:5000/update?pickup=0&broken=1&lost=0&remaining=0&nogun=1
def update_data(nogun):
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = f'UPDATE gun SET pickup={pickup} , broken=%s , lost=%s , remaining=%s  WHERE nogun=%s'
    val = (pickup, broken, lost, remaining, nogun)
    mycursor.execute(sql,val)
    mydb.commit()
    mycursor.close()
    mydb.close()

# localhost:5000/delete?nogun=3
def delete_data(nogun):
    mydb = ConnectorMysql()
    mycursor = mydb.cursor()
    sql = "DELETE  FROM gun WHERE nogun={}".format(nogun)
    mycursor.execute(sql)
    mydb.commit()
    mycursor.close()
    mydb.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
